  manifest:
      remotes:                                                
          - name: zmkfirmware                               
            url-base: https://github.com/zmkfirmware          
          - name: nicekeyboards                               
            url-base: https://github.com/nicekeyboards
      projects:
          - name: zmk                                         
            remote: zmkfirmware
            revision: main                                    
            import: app/west.yml                            
          - name: zmk-hardware-nicekeyboards  
            remote: nicekeyboards         
            revision: main
            import: config/west.yml                           
      self:
          path: config  
